
set MATLAB=C:\Program Files\MATLAB\R2022b

"%MATLAB%\bin\%MATLAB_WIN_VER%\gmake" -f Code4capSensor.mk  GENERATE_ASAP2=0 OPTS="-DEXT_MODE -DEXTMODE_STATIC -DEXTMODE_STATIC_SIZE=2048 -DON_TARGET_WAIT_FOR_START=0 -DTID01EQ=0"
